services:
  # Backend Service
  - type: web
    name: bakery-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SERVER_PORT
        value: 8080
    healthCheckPath: /api/health
